/**
 * Mock data per la pagina Clients Management
 */

import { Client } from "../types/types";

export const clients: Client[] = [
  {
    id: "CLI-001",
    name: "Acme Corporation",
    email: "contact@acme.com",
    company: "Acme Corp",
    status: "active",
    plan: "enterprise",
    createdAt: "2024-01-15",
    lastContact: "2024-12-10",
    projects: 12,
    revenue: 24999,
  },
  {
    id: "CLI-002",
    name: "TechStart SRL",
    email: "info@techstart.io",
    company: "TechStart",
    status: "active",
    plan: "professional",
    createdAt: "2024-02-20",
    lastContact: "2024-12-08",
    projects: 5,
    revenue: 4990,
  },
  {
    id: "CLI-003",
    name: "Digital Agency Ltd",
    email: "hello@digitalagency.com",
    company: "Digital Agency",
    status: "active",
    plan: "basic",
    createdAt: "2024-03-10",
    lastContact: "2024-12-05",
    projects: 3,
    revenue: 990,
  },
  {
    id: "CLI-004",
    name: "Innovation Labs",
    email: "contact@innovationlabs.io",
    company: "Innovation Labs",
    status: "active",
    plan: "enterprise",
    createdAt: "2024-01-05",
    lastContact: "2024-12-12",
    projects: 18,
    revenue: 35999,
  },
  {
    id: "CLI-005",
    name: "StartupXYZ",
    email: "founder@startupxyz.com",
    company: "StartupXYZ",
    status: "pending",
    plan: "basic",
    createdAt: "2024-12-01",
    projects: 0,
    revenue: 0,
  },
  {
    id: "CLI-006",
    name: "Consulting Group",
    email: "info@consultinggroup.biz",
    company: "Consulting Group",
    status: "inactive",
    plan: "professional",
    createdAt: "2023-11-15",
    lastContact: "2024-06-20",
    projects: 2,
    revenue: 1990,
  },
  {
    id: "CLI-007",
    name: "Global Solutions Inc",
    email: "sales@globalsolutions.com",
    company: "Global Solutions",
    status: "active",
    plan: "enterprise",
    createdAt: "2024-04-22",
    lastContact: "2024-12-11",
    projects: 24,
    revenue: 49999,
  },
  {
    id: "CLI-008",
    name: "Small Business Co",
    email: "owner@smallbiz.local",
    company: "Small Business Co",
    status: "active",
    plan: "basic",
    createdAt: "2024-08-10",
    lastContact: "2024-12-09",
    projects: 1,
    revenue: 99,
  },
];
